calendar_valentine/calendar_auth/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

import calendar_auth.views as calendar_auth

urlpatterns = [
    path('user/create/',
         calendar_auth.CalendarUserCreateView.as_view(),
         name='user_create'),
    # path('cards/', cards.cards_list),
    path('login/',
         LoginView.as_view(),
         name='login'),
    path('logout/',
         LogoutView.as_view(),
         name='logout'),
]

calendar_valentine/calendar_valentine/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include(('cards.urls', 'cards'), namespace='cards')),
    path('admin/', admin.site.urls),
    path('calendar_auth/', include(('calendar_auth.urls', 'calendar_auth'), namespace='calendar_auth')),
]

calendar_valentine/cards/urls.py
from django.urls import path, re_path
import cards.views as cards


urlpatterns = [
    path('', cards.index, name='index'),
    # path('cards/', cards.cards_list),
    path('cards/',
         cards.CardsListView.as_view(),
         name='cards_list'),
    path('cards/<slug:slug>/',
         cards.CardDetailView.as_view(template_name='cards/card_detail.html'),
         name='card_detail'),
]

calendar_valentine/calendar_auth/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class CalendarUser(AbstractUser):
    email = models.EmailField('email address', unique=True)
    d_birth = models.DateField(blank=True, null=True)
    bio = models.TextField(blank=True)

calendar_valentine/cards/models.py
from django.db import models
from django.urls import reverse


class Card(models.Model):
    name = models.CharField(max_length=64)
    title = models.CharField(max_length=64)
    body = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(primary_key=True, max_length=250, unique=True)

    def get_absolute_url(self):
        return reverse('cards:card_detail', args=[str(self.slug)])

    def __str__(self):
        return f'{self.name}'


class Master(models.Model):
    name = models.CharField(max_length=64)
    body = models.TextField()

    def __str__(self):
        return self.name, self.body

calendar_valentine/calendar_auth/forms.py
from django.contrib.auth.forms import UserCreationForm

from calendar_auth.models import CalendarUser


class CalendarUserCreateForm(UserCreationForm):

    class Meta:
        model = CalendarUser
        fields = ('username', 'email', 'password1', 'password2')

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     for field_name, field_obj in self.fields.items():

calendar_valentine/calendar_auth/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import CreateView

from calendar_auth.forms import CalendarUserCreateForm
from calendar_auth.models import CalendarUser


class CalendarUserCreateView(CreateView):
    model = CalendarUser
    success_url = '/'
    form_class = CalendarUserCreateForm

calendar_valentine/cards/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.views.generic import ListView, DetailView

from cards.models import Card


def index(request):
    cards = Card.objects.all()
    context = {
        'card_list': cards,
    }
    return render(request, 'cards/index.html', context=context)


class CardsListView(ListView):
    model = Card


class CardDetailView(DetailView):
    model = Card
    context_object_name = 'card'

    def get_object(self, queryset=None):
        return get_object_or_404(Card, slug__iexact=self.kwargs['slug'])


# def cards_list(request):
#     cards = Card.objects.all()
#     context = {
#         'cards': cards,
#     }
#     return render(request, 'cards/card_list.html', context=context)


# def card_details(request, card_id):
#     cards = Card.objects.all()
#     card = get_object_or_404(Card, pk=card_id)
#     context = {
#         'card': card,
#         'cards': cards,
#
#     }
#     return render(request, 'cards/card_detail.html', context=context)
#

calendar_valentine/calendar_auth/templates/calendar_auth/calendaruser_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create</title>
</head>
<body>
<div class="user_creation-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="save">
    </form>
</div>
</body>
</html>

calendar_valentine/cards/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>
        {% block page_title %}
        {% endblock %}
    </title>
</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<div class="container=md">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-md">
            <a class="navbar-brand" href="{% url 'cards:index' %}">День Святого Валентина</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'cards:index' %}">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'cards:cards_list' %}">Карточки
                            дней</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>


{% block main_container %}

{% endblock %}
</body>
</html>

calendar_valentine/cards/templates/cards/card_detail.html
{% extends 'base.html' %}

{% block page_title %}
    Карточки дней
{% endblock %}


{% block main_container %}
    <div class="container-md">
        <div>
            <p>
                <a href="{% url 'cards:cards_list' %}">Ко всем карточкам</a>
            </p>
        </div>
        <h2>{{ card.title }}</h2>
        <div class="card" style="width: 24rem;">
            <img src="..." class="card-img-top" alt="...">
            <div class="card-body">

                <p class="card-text">{{ card.body }}</p>
            </div>
            <div class="card-body">
                <a href="{{ card.get_previous_by_pub_date.get_absolute_url }}" class="card-link">Предыдущий день</a>
                <a href="{{ card.get_next_by_pub_date.get_absolute_url }}" class="card-link">Следующий день</a>
            </div>
        </div>
    </div>


{% endblock %}

calendar_valentine/cards/templates/cards/card_list.html
{% extends 'base.html' %}

{% block page_title %}
    Карточки дней
{% endblock %}

{% block main_container %}



    {% if user.is_authenticated %}
        <div class="container-md">
        <h2>Карточки дней</h2>
            <div><a href="{% url 'cards:index' %}">На главную</a></div>
            <ul>
                {% for card in card_list %}
                    <li>
                        {#                    <a href="/cards/{{ card.id }}/">{{ card }}</a>#}
                        <a href="{{ card.get_absolute_url }}">{{ card }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% else %}
        <div class="container-md">
            <p>Пожалуйста, авторизируйтесь</p>
            <p><a href="{% url 'calendar_auth:login' %}">Войти</a></p>

            <p><a href="{% url 'calendar_auth:user_create' %}">Регистрация</a></p>
        </div>
    {% endif %}
{% endblock %}

calendar_valentine/cards/templates/cards/index.html
{% extends 'base.html' %}


{% block page_title %}
    Адвент СВ
{% endblock %}

{% block main_container %}
    <div class="container">
        <h2>Добро пожаловать в адвент-календарь ко дню Святого Валентина!</h2>
    </div>

    <div class="container">

        {#        <a href="/">Main</a>#}

        <p>
            {% if user.is_authenticated %}
                <a href="{% url 'cards:cards_list' %}">Карточки дней</a>
            {% endif %}
        </p>
        <p>
            {% if user.is_authenticated %}
                <a href="{% url 'calendar_auth:logout' %}">Выйти ({{ user.username }})</a>
            {% else %}
                <a href="{% url 'calendar_auth:login' %}">Войти</a>
            {% endif %}
        </p>
        <p>
            {% if not user.is_authenticated %}
                <a href="{% url 'calendar_auth:user_create' %}">Регистрация</a>
            {% endif %}
        </p>

    </div>


{% endblock %}